### ISSUE TITLE
Cannot find module 'concat-map' on Windows

### ISSUE THREAD

**Issue by Siecje** [mhoyer/todomvc-aurelia#8]
After installing dependencies when I run gulp I get this error

``` bash
Cody@CODETOP ~/Desktop/todomvc-aurelia (master)
$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\Cody\Desktop\todomvc-aurelia\node_modules\gu
lp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\node_mo
dules\brace-expansion\index.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by mhoyer** [comment]
@Siecje, I just ran these lines as explained in my `README`:

> Clone the repository:
> 
>    `git clone https://github.com/mhoyer/todomvc-aurelia`
> 
> Install jspm and npm packages:
> 
>    `npm install`
>    `jspm install`
> 
> Simply build, test, bundle, export: `gulp`

It worked for me and my machine.
1. Following your shell snippet it looks like you were trying to run `gulp` under a `bash`. Is it `cygwin` or `mysys-bash`?
2. Did you monitor the `npm install` and `jspm install` output? I had trouble with some binary component (but not gulp related IIRC).

**Comment by Siecje** [comment]
I was using Git Bash. It appeared everything was installed.

**Comment by mhoyer** [comment]
Strange. I also just tried it with git bash, works on my machine. What is your versions of NodeJS and gulp?

```
$ cd todomvc-aurelia

$ node --version
v0.10.18

$ gulp --version
[23:15:42] CLI version 3.8.5
[23:15:42] Local version undefined

$ npm ls gulp
todomvc-aurelia@0.2.0 d:\Temp\todomvc-aurelia
└── gulp@3.8.11
```

**Comment by Siecje** [comment]
``` bash

Siecje@CODETOP ~/Desktop/todomvc-aurelia (master)
$ node --version
v0.12.0

Siecje@CODETOP ~/Desktop/todomvc-aurelia (master)
$ gulp --version
[18:49:57] CLI version 3.8.11
[18:49:57] Local version 3.8.11

Siecje@CODETOP ~/Desktop/todomvc-aurelia (master)
$ npm ls gulp
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\bro
wser-sync\node_modules\glob-watcher\node_modules\gaze\node_modules\globule requi
res lodash@'~1.0.1' but will load
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\bro
wser-sync\node_modules\lodash,
npm WARN unmet dependency which is version 2.4.1
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\gul
p-jshint\node_modules\jshint requires minimatch@'1.0.x' but will load
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\gul
p-jshint\node_modules\minimatch,
npm WARN unmet dependency which is version 2.0.3
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\gul
p-jshint\node_modules\rcloader requires lodash@'~2.4.1' but will load
npm WARN unmet dependency C:\Users\Siecje\Desktop\todomvc-aurelia\node_modules\gul
p-jshint\node_modules\lodash,
npm WARN unmet dependency which is version 3.5.0
todomvc-aurelia@0.2.0 C:\Users\Siecje\Desktop\todomvc-aurelia
└── gulp@3.8.11

```
